export const cards = [
    {name: "death", url: require("./img/cards/Arcana_Death.jpg")},
    {name: "emperor", url: require("./img/cards/Arcana_Emperor.jpg")},
    {name: "judge", url: require("./img/cards/Arcana_Judgement.jpg")},
    {name: "just", url: require("./img/cards/Arcana_Justice.jpg")},
    {name: "magician", url: require("./img/cards/Arcana_Magician.jpg")},
    {name: "rival", url: require("./img/cards/Arcana_Rival.jpg")},
    {name: "chariot", url: require("./img/cards/Arcana_Sky_Chariot.jpg")},
    {name: "temperance", url: require("./img/cards/Arcana_Temperance.jpg")},
    {name: "beast", url: require("./img/cards/Arcana_The_Beast.jpg")},
    {name: "charnok", url: require("./img/cards/Hero_Charnok.jpg")},
    {name: "minotaur", url: require("./img/cards/Hero_Minotaur.jpg")},
    {name: "mozu", url: require("./img/cards/Hero_Mozu.jpg")},
    {name: "pakko", url: require("./img/cards/Hero_Pakko.jpg")},
    {name: "ramsay", url: require("./img/cards/Hero_Ramsay.jpg")},
    {name: "tyto", url: require("./img/cards/Hero_Tyto.jpg")},
    {name: "voden", url: require("./img/cards/Hero_Voden.jpg")},
    {name: "common", url: require("./img/cards/Juice_Common.png")},
    {name: "xenobia", url: require("./img/cards/Hero_Xenobia.jpg")},
    {name: "twins", url: require("./img/cards/Arcana_Twins.jpg")},
    {name: "world", url: require("./img/cards/Arcana_World.jpg")},
  ];